### ISSUE TITLE
Contracts 2.0

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#244]
Functional Requirements:
- [x] [Reference implementation of POAP](https://github.com/nevermined-io/contracts/issues/246)
- [x] [NFTs as access control as expiring subscriptions](https://github.com/nevermined-io/contracts/issues/245)
- [x] [Lazy Minting. NFTs are minted during the purchase of the asset](https://github.com/nevermined-io/contracts/issues/260)
- [x] [Marketplace fee](https://github.com/nevermined-io/contracts/issues/262)
- [x] [Governable configuration](https://github.com/nevermined-io/contracts/issues/261)
- [x] [NFT Transfers in one contract call](https://github.com/nevermined-io/contracts/issues/263)
- [x] [Validate if MultiSig works properly](https://github.com/nevermined-io/contracts/issues/271)
- [x] https://github.com/nevermined-io/internal/issues/200
- [x] https://github.com/nevermined-io/contracts/issues/305

Non Functional Requirements:
- [x] [Integration tests for deployed contracts](https://github.com/nevermined-io/contracts/pull/285)
- [x] [Analyze and reduce gas cost for Service Agreements](https://github.com/nevermined-io/contracts/issues/236)
- [x] [Add validation of external conditions into access conditions](https://github.com/nevermined-io/contracts/issues/234)
- [x] [Upgrade to latest OZ + dependencies](https://github.com/nevermined-io/contracts/issues/247)
- [x] [Remove dependant bot alerts](https://github.com/nevermined-io/contracts/issues/248)
- [x] [Upgrade contract tools to latest versions or get rid of it](https://github.com/nevermined-io/contracts/issues/249)
- [x] https://github.com/nevermined-io/contracts/issues/275
- [x] https://github.com/nevermined-io/contracts/pull/300
