### ISSUE TITLE
Contracts 2.1

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#307]
Requirements:

- [x] https://github.com/nevermined-io/contracts/issues/325
- [x] https://github.com/nevermined-io/contracts/issues/327
- [x] #338
- [x] #316 
- [x] Update to hardhat `v2.10.x`: https://github.com/nevermined-io/contracts/pull/339
- [x] https://github.com/nevermined-io/contracts/issues/311
- [x] Automate the execution of security reports (nightly) - https://github.com/nevermined-io/contracts/issues/295
- [x] #337 
- [x] [Use `geth` instead of `openethereum` by default in `nvm-tools`](https://github.com/nevermined-io/tools/pull/117)
- [x] https://github.com/nevermined-io/contracts/pull/389
- [x] [Automate contracts code deployment into Etherscan / Polygonscan](https://github.com/nevermined-io/contracts/issues/151) (@kike)
