### ISSUE TITLE
Fix the Contracts reported issues by the auditors

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#65]
### Static Analysis

- [x] #66 - Tautology Clauses
- [x] #67 - Arbitrary Re-Entrancy

### Manual Review

Registration
- [x] #70 
- [x] #71 - DIR-01M: Provenance Out of Sync
- [x] #72 - DIR-02M: Ineffectual Cap Validation
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78 - Potential Token Incompatibility
- [x] #79

### Code Style

- [x] #80
- [x] #81
- [x] #82 - DIDRegistryLibrary Code Style Findings
- [x] #83
